routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\UserController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ConfigController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
        return view('welcome');
    });

Auth::routes();

Route::group(['middleware' => ['auth']], function() {

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Config

Route::resource('config', ConfigController::class);

// User

Route::resource('users', UserController::class);

// Profile

    Route::resource('profile', ProfileController::class);

    Route::post('/profile/{id}', [App\Http\Controllers\ProfileController::class, 'change'])->name('profile.change');

});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $users = User::all();

        return view('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $user = null;
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {

        $request->validate([
            'name' => 'required',
            'email'=> 'required',
            'password' => 'required',
            'password_confirmation' => 'required',
            'photo' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048',
            
        ]);


        $photo = $request->file('photo');
        $fileName = time() . '.' . $photo->getClientOriginalExtension();
        $photo->move(public_path('Profile/photos'), $fileName);

        $user = new User;
        $user->name = $request->input('name');
        $user->email = $request->input('email');
        $user->street_address = $request->input('street_address');
        $user->city = $request->input('city');
        $user->taluka = $request->input('taluka');
        $user->district = $request->input('district');
        $user->pin_code = $request->input('pin_code');
        $user->state = $request->input('state');
        $user->status = $request->input('status', 'active');
        $password = $request->input('password');
        $user->password = Hash::make($password);
        $cnfpsw = $request->input('password_confirmation');
        $user->photo = $fileName;
        
       // dd($user);

        if ($password === $cnfpsw) {

            $user->save();

            return redirect()->route('users.index')
                ->with('success_message', 'Mandal successfully Create');
        } else {
            return redirect()->back()
                ->with('error', 'Password and Confirm Password must be same !');
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(User $user)
    {
        return view('user.edit', [
            'user' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {

        $request->validate([
            'name' => 'required',
            'email'=> 'required',
            'status'=> 'required',
            
        ]);

        $user = User::find($id);

        if ($request->hasFile('photo')) {

            $photo = $request->file('photo');
            $fileName = time() . '.' . $photo->getClientOriginalExtension();
            $photo->move(public_path('Profile/photos'), $fileName);

            if ($user->photo) {
                $oldPhotoPath = public_path('Profile/photos/') . $user->photo;
                if (file_exists($oldPhotoPath)) {
                    unlink($oldPhotoPath);
                }
            }
            $user->photo = $fileName;
        }

        
        $user->name = $request->input('name');
        $user->email = $request->input('email');
        $user->street_address = $request->input('street_address');
        $user->city = $request->input('city');
        $user->taluka = $request->input('taluka');
        $user->district = $request->input('district');
        $user->pin_code = $request->input('pin_code');
        $user->state = $request->input('state');
        $user->status = $request->input('status');
        $user->update();
        return redirect()->route('users.index')
            ->with('success_message', 'Mandal updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $user = User::find($id);
        $user->delete();

        return redirect()->route('users.index') 
                ->with('success_message',' Mandal successfully deleted');
    }
}

resources/views/user/create.blade.php
@include('layouts.partials.header')
@include('layouts.partials.sidebar')
<div class="app-main flex-column flex-row-fluid" id="kt_app_main">
	<div class="d-flex flex-column flex-column-fluid">
		<div id="kt_app_toolbar" class="app-toolbar pt-7 pt-lg-10">
			<div id="kt_app_toolbar_container" class="app-container container-fluid d-flex align-items-stretch">
				<div class="app-toolbar-wrapper d-flex flex-stack flex-wrap gap-4 w-100">
					<div class="page-title d-flex flex-column justify-content-center gap-1 me-3">
						<h1 class="page-heading d-flex flex-column justify-content-center text-dark fw-bold fs-3 m-0">User Form</h1>
						<ul class="breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-0">
							<li class="breadcrumb-item text-muted">
								<a href="{{ route('home') }}" class="text-muted text-hover-primary">Home</a>
							</li>
							<li class="breadcrumb-item">
								<span class="bullet bg-gray-400 w-5px h-2px"></span>
							</li>
							<li class="breadcrumb-item text-muted">
								<a href="{{ route('users.index') }}" class="text-muted text-hover-primary">List</a>
							</li>
							<li class="breadcrumb-item">
								<span class="bullet bg-gray-400 w-5px h-2px"></span>
							</li>
							<li class="breadcrumb-item text-muted">Create</li>
						</ul>
					</div>
					<div class="d-flex align-items-center gap-2 gap-lg-3">
						<a href="{{ route('users.index') }}" class="btn btn-sm btn-danger me-5">Back</a>
					</div>
				</div>
			</div>
		</div>
		<div id="kt_app_content" class="app-content flex-column-fluid">
			<div id="kt_app_content_container" class="app-container container-fluid">
				@if (\Session::has('error'))
				    <div class="alert alert-danger alert-dismissible fade show" role="alert">
				      <strong>{!! \Session::get('error') !!}</strong>
				      <button type="button" class="btn-close btn-sm" data-bs-dismiss="alert" aria-label="Close"></button>
				    </div>
				@endif
				<form method="POST" action="{{ route('users.store') }}" accept-charset="UTF-8" id="create_user_form" name="create_user_form" class="form d-flex flex-column flex-lg-row" enctype="multipart/form-data">
					{{ csrf_field() }}
					<div class="d-flex flex-column flex-row-fluid gap-7 gap-lg-10 me-lg-10 mb-7">
						<div class="d-flex flex-column gap-7 gap-lg-10">
							<div class="card card-flush py-4">
								<div class="card-header">
									<div class="card-title">
										<h2>User Details</h2>
									</div>
								</div>
								<div class="card-body pt-0">
									<div class="row gx-10 mb-5">
										<div class="col-lg-6">
											<label class="required form-label">Name</label>
											<input type="text" name="name" class="form-control mb-2 @error('name') is-invalid @enderror" placeholder="Name" value="{{old('name')}}" />

											@error('name')
	                                        <span class="invalid-feedback" role="alert">
	                                            <strong>{{ $message }}</strong>
	                                        </span>
	                                    	@enderror
										</div>
										<div class="col-lg-6">
											<label class="required form-label">Email</label>
											<input type="email" name="email" class="form-control mb-2 @error('email') is-invalid @enderror" placeholder="Email" value="{{old('email')}}" />

											@error('email')
	                                        <span class="invalid-feedback" role="alert">
	                                            <strong>{{ $message }}</strong>
	                                        </span>
	                                    	@enderror
										</div>
									</div>
									<div class="row gx-10 mb-5">
										<div class="col-lg-6">
											<label class="form-label">Street Address</label>
											<input type="text" name="street_address" class="form-control mb-2 @error('street_address') is-invalid @enderror" placeholder="Street address" value="{{old('street_address')}}" />
										</div>
										<div class="col-lg-6">
											<label class="form-label">City</label>
											<input type="text" name="city" class="form-control mb-2 @error('city') is-invalid @enderror" placeholder="City" value="{{old('city')}}" />
										</div>
									</div>
									<div class="row gx-10 mb-5">
										<div class="col-lg-6">
											<label class="form-label">Taluka</label>
											<input type="text" name="taluka" class="form-control mb-2 @error('taluka') is-invalid @enderror" placeholder="Taluka" value="{{old('taluka')}}" />
										</div>
										<div class="col-lg-6">
											<label class="form-label">District</label>
											<input type="text" name="district" class="form-control mb-2 @error('district') is-invalid @enderror" placeholder="District" value="{{old('district')}}" />
										</div>
									</div>
									<div class="row gx-10 mb-5">
										<div class="col-lg-6">
											<label class="form-label">State</label>
											<input type="text" name="state" class="form-control mb-2 @error('state') is-invalid @enderror" placeholder="State" value="{{old('state')}}" />
										</div>
										<div class="col-lg-6">
											<label class="form-label">Pin No</label>
											<input type="number" name="pin_code" class="form-control mb-2 @error('pin_code') is-invalid @enderror" placeholder="Pin code" value="{{old('pin_code')}}" />
										</div>
									</div>
									<div class="row gx-10 mb-5">
										<div class="col-lg-6">
											<label class="required form-label">Password</label>
											<input type="password" name="password" class="form-control mb-2 @error('password') is-invalid @enderror" placeholder="Password" value="" />
											@error('password')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
										</div>
										<div class="col-lg-6">
											<label class="required form-label">Repeat Password</label>
											<input type="password" name="password_confirmation" class="form-control mb-2 @error('password_confirmation') is-invalid @enderror" placeholder="Repeat password" />
											@error('password_confirmation')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="d-flex justify-content-end">
							<a href="{{ route('users.index') }}" class="btn btn-sm btn-light me-5">Cancel</a>
							<button type="submit" value="Add" class="btn btn-sm btn-primary">
								<span class="indicator-label">Save Changes</span>
							</button>
						</div>
					</div>
					<div class="d-flex flex-column gap-7 gap-lg-10 w-100 w-lg-300px">
						<div class="card card-flush py-4">
							<div class="card-header">
								<div class="card-title">
									<h5>Profile Photo</h5>
								</div>
							</div>
							<div class="card-body text-center pt-0">
							    <style>
							        .image-input-placeholder { background-image: url({{ asset('admin/dist/assets/media/svg/files/blank-image.svg') }}); }
							        [data-bs-theme="dark"] .image-input-placeholder { background-image: url({{ asset('admin/dist/assets/media/svg/files/blank-image-dark.svg') }}); }
							    </style>
							    <div class="image-input image-input-empty image-input-outline image-input-placeholder mb-3" data-kt-image-input="true">
							        <div class="image-input-wrapper w-150px h-150px"></div>
							        <label class="btn btn-icon btn-circle btn-active-color-primary w-25px h-25px bg-body shadow" data-kt-image-input-action="change" data-bs-toggle="tooltip" title="Change avatar">
							            <i class="ki-outline ki-pencil fs-7"></i>
							            <input type="file" name="photo" accept=".png, .jpg, .jpeg" />
							            <input type="hidden" name="custom_delete_photo" />
							        </label>
							        <span class="btn btn-icon btn-circle w-25px h-25px bg-body shadow" data-kt-image-input-action="cancel" data-bs-toggle="tooltip" title="Cancel avatar">
							            <i class="ki-outline ki-cross fs-2"></i>
							        </span>
							        <span class="btn btn-icon btn-circle w-25px h-25px bg-body shadow" data-kt-image-input-action="remove" data-bs-toggle="tooltip" title="Remove avatar">
							            <i class="ki-outline ki-cross fs-2"></i>
							        </span>
							    </div>
							</div>
						</div>
						<div class="card card-flush py-4">
							<div class="card-header">
								<div class="required card-title">
									<h5>Status</h5>
								</div>
							</div>
							<div class="card-body pt-0">
								<select name="status" aria-label="Select a status" data-control="select2" data-placeholder="Select status" class="form-select @error('status') is-invalid @enderror">
	                                <option value="">Select Status</option>
	                                <option value="active" {{ old('status') == 'active' ? 'selected' : null }}>Active</option>
	                                <option value="inactive" {{ old('status') == 'inactive' ? 'selected' : null }}>Inactive</option>
                            	</select>
                            	@error('status')
	                                <span class="invalid-feedback" role="alert">
	                                    <strong>{{ $message }}</strong>
	                                </span>
                            	@enderror
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
@include('layouts.partials.footer')

resources/views/user/index.blade.php
@include('layouts.partials.header')
@include('layouts.partials.sidebar')
<div class="app-main flex-column flex-row-fluid" id="kt_app_main">
    <div class="d-flex flex-column flex-column-fluid">
		<div id="kt_app_toolbar" class="app-toolbar pt-7 pt-lg-10">
			<div id="kt_app_toolbar_container" class="app-container container-fluid d-flex align-items-stretch">
				<div class="app-toolbar-wrapper d-flex flex-stack flex-wrap gap-4 w-100">
					<div class="page-title d-flex flex-column justify-content-center gap-1 me-3">
						<h1 class="page-heading d-flex flex-column justify-content-center text-dark fw-bold fs-3 m-0">User List</h1>
						<ul class="breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-0">
							<li class="breadcrumb-item text-muted">
								<a href="{{ route('home') }}" class="text-muted text-hover-primary">Home</a>
							</li>
							<li class="breadcrumb-item">
								<span class="bullet bg-gray-400 w-5px h-2px"></span>
							</li>
							<li class="breadcrumb-item text-muted">User Management</li>
							<li class="breadcrumb-item">
								<span class="bullet bg-gray-400 w-5px h-2px"></span>
							</li>
							<li class="breadcrumb-item text-muted">Users</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div id="kt_app_content" class="app-content flex-column-fluid">
			<div id="kt_app_content_container" class="app-container container-fluid">
				@if(Session::has('success_message'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <strong>{!! \Session::get('success_message') !!}</strong>
                        <button type="button" class="btn-close btn-sm" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                @endif
                @if (\Session::has('error'))
				    <div class="alert alert-danger alert-dismissible fade show" role="alert">
				      <strong>{!! \Session::get('error') !!}</strong>
				      <button type="button" class="btn-close btn-sm" data-bs-dismiss="alert" aria-label="Close"></button>
				    </div>
				@endif
				<div class="card">
					<div class="card-header border-0 pt-6">
						<div class="card-title">
							<div class="d-flex align-items-center position-relative my-1">
								<i class="ki-outline ki-magnifier fs-3 position-absolute ms-5"></i>
								<input type="text" data-kt-user-table-filter="search" class="form-control form-control-solid w-250px ps-13" placeholder="Search User" />
							</div>
						</div>
						<div class="card-toolbar">
							<div class="d-flex justify-content-end" data-kt-user-table-toolbar="base">
								<a type="button" class="btn btn-sm btn-primary me-3" href="{{ route('users.create')}}">
								<i class="ki-outline ki-plus fs-2"></i>Add User</a>
							</div>
							<div class="d-flex justify-content-end align-items-center d-none" data-kt-user-table-toolbar="selected">
								<div class="fw-bold me-5">
								<span class="me-2" data-kt-user-table-select="selected_count"></span>Selected</div>
								<button type="button" class="btn btn-danger" data-kt-user-table-select="delete_selected">Delete Selected</button>
							</div>
						</div>
					</div>
					<div class="card-body py-4">
						<table class="table align-middle table-row-dashed fs-6 gy-5" id="kt_table_users">
							<thead>
								<tr class="text-start text-muted fw-bold fs-7 text-uppercase gs-0">
									<th class="min-w-125px">Sr No</th>
									<th class="min-w-125px">Name</th>
									<th class="min-w-125px"></th>
									<th class="min-w-125px">City</th>
									<th class="min-w-125px">Taluka</th>
									<th class="min-w-125px">Status</th>
									<th class="min-w-125px">Actions</th>
								</tr>
							</thead>
							<tbody class="text-gray-600 fw-semibold">
								<?php $i = 1; ?>
								@foreach($users as $user)
								<tr>
									<td>{{ $i++ }}</td>
									<td class="d-flex align-items-center">
										<!--begin:: Avatar -->
										<div class="symbol symbol-circle symbol-50px overflow-hidden me-3">
                                            @if(!is_null($user->photo))
											<span>
												<div class="symbol-label">
													<img src="{{ asset('Profile/photos/' . $user->photo) }}" alt="Emma Smith" class="w-100" />
												</div>
											</span>
											@else
											<span>
												<div class="symbol-label">
													<img src="{{ asset('admin/dist/assets/media/svg/avatars/blank.svg') }}" alt="Emma Smith" class="w-100" />
												</div>
											</span>
											@endif
										</div>
										<div class="d-flex flex-column">
											<a href="{{ route('users.edit',$user->id) }}" class="text-gray-800 text-hover-primary mb-1">{{ $user->name }}</a>
											<span>{{ $user->email }}</span>
										</div>
									</td>
									<td></td>
									<td>{{ $user->city }}</td>
									<td>{{ $user->taluka }}</td>
									<td>@if($user->status == 'active')
										<div class="badge badge-light-success fw-bold">Active</div>
										@elseif($user->status == 'inactive')
										<div class="badge badge-light-danger fw-bold">Inactive</div>
										@endif
									</td>
									<td>
										<a href="#" class="btn btn-light btn-active-light-primary btn-flex btn-center btn-sm" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">Actions
										<i class="ki-outline ki-down fs-5 ms-1"></i></a>
										<div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-semibold fs-7 w-125px py-4" data-kt-menu="true">
											@if($user->email === Auth::user()->email )
											<div class="menu-item px-3">
												<a href="{{ route('users.edit',$user->id) }}" class="menu-link px-3">Edit</a>
											</div>
											@else
											<div class="menu-item px-3">
                                                    <a href="{{ route('users.edit',$user->id) }}" class="menu-link px-3">Edit</a>
                                                </div>
                                                <div class="menu-item px-3">
                                                    <form method="POST" action="{{ route('users.destroy', $user['id']) }}" accept-charset="UTF-8">
                                                        <input name="_method" value="DELETE" type="hidden">
                                                        {{ csrf_field() }}
                                                        <button type="submit" title="delete" class="btn btn-sm w-100 menu-link px-3" data-id="#" onclick="return confirm(&quot;Click Ok to delete User.&quot;)" >
                                                            Delete
                                                        </button>
                                                    </form>
                                                </div>
                                                @endif
										</div>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@include('layouts.partials.footer')

<script>var hostUrl = "assets/";</script>
<script src="{{ asset('admin/dist/assets/plugins/global/plugins.bundle.js') }}"></script>
<script src="{{ asset('admin/dist/assets/js/scripts.bundle.js') }}"></script>
<!--end::Global Javascript Bundle-->
<!--begin::Vendors Javascript(used for this page only)-->
<script src="{{ asset('admin/dist/assets/plugins/custom/datatables/datatables.bundle.js') }}"></script>
<!--end::Vendors Javascript-->
<!--begin::Custom Javascript(used for this page only)-->
<script src="{{ asset('admin/dist/assets/js/custom/apps/user-management/users/list/table.js') }}"></script>
<script src="{{ asset('admin/dist/assets/js/custom/apps/user-management/users/list/export-users.js') }}"></script>
<script src="{{ asset('admin/dist/assets/js/custom/apps/user-management/users/list/add.js') }}"></script>
<script src="{{ asset('admin/dist/assets/js/widgets.bundle.js') }}"></script>
<script src="{{ asset('admin/dist/assets/js/custom/widgets.js') }}"></script>
<script src="{{ asset('admin/dist/assets/js/custom/apps/chat/chat.js') }}"></script>
<script src="{{ asset('admin/dist/assets/js/custom/utilities/modals/upgrade-plan.js') }}"></script>
<script src="{{ asset('admin/dist/assets/js/custom/utilities/modals/create-campaign.js') }}"></script>
<script src="{{ asset('admin/dist/assets/js/custom/utilities/modals/users-search.js') }}"></script>